<%@ page language="C#" autoeventwireup="true" inherits="Home_TrendCharts_FC3D_FC3D_HSWH, App_Web_1hqvi6z9" enableEventValidation="false" %>

<%@ Register Src="../../Home/Room/UserControls/WebFoot.ascx" TagName="WebFoot" TagPrefix="uc1" %>
<%@ Register Src="../../UserControls/Head.ascx" TagName="Head" TagPrefix="uc2" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>福彩3D 和数尾号码分区表-彩票走势图表和数据分析－<%=_Site.Name %></title>
    <meta name="keywords" content="福彩3D 和数尾号码分区表" />
    <meta name="description" content="福彩3D 和数尾号码分区表、彩票走势图表和数据分析。" />
    <link href="../../Home/Room/Style/common.css" rel="stylesheet" type="text/css" />
    <link href="../../Home/Room/Style/StyleSheet.css" rel="stylesheet" type="text/css" />
    <link href="../../Home/Room/Style/zbuy.css" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="../../favicon.ico" />
    <link href="../../Home/Room/Style/zst.css" rel="stylesheet" type="text/css" />

    <script src="../../JavaScript/jquery-1.4.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function() {
            $("table tr:odd").css("background-color", "#f8f2f2");
            $("table tr:first").css("background-color", "#ffebeb").css("color", "#393838").css("font-weight", "bold");
           
        });
    </script>

</head>
<body>
    <form id="form1" runat="server">
            <uc2:head id="Head2" runat="server" />
            <div class="wrap">
<div class="zst_top">
<dl><dt>3D和数尾号码分区表走势图</dt> <dd></dd></dl>
</div>  
</div>
    <div class="wrap">
<table>
<tbody>
 <tr>
                                                <td width="88" height="30">
                                                    和数尾
                                                </td>
                                                <td colspan="3">
                                                    0
                                                </td>
                                                <td colspan="3">
                                                    1
                                                </td>
                                                <td colspan="3">
                                                    2
                                                </td>
                                                <td colspan="3">
                                                    3
                                                </td>
                                                <td colspan="3">
                                                    4
                                                </td>
                                                <td colspan="3">
                                                    5
                                                </td>
                                                <td colspan="3">
                                                    6
                                                </td>
                                                <td colspan="3">
                                                    7
                                                </td>
                                                <td colspan="2">
                                                    8
                                                </td>
                                                <td colspan="2">
                                                    9
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    和数值
                                                </td>
                                                <td>
                                                    0
                                                </td>
                                                <td>
                                                    10
                                                </td>
                                                <td>
                                                    20
                                                </td>
                                                <td>
                                                    1
                                                </td>
                                                <td>
                                                    11
                                                </td>
                                                <td>
                                                    21
                                                </td>
                                                <td>
                                                    2
                                                </td>
                                                <td>
                                                    12
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                                <td>
                                                    3
                                                </td>
                                                <td>
                                                    13
                                                </td>
                                                <td>
                                                    23
                                                </td>
                                                <td>
                                                    4
                                                </td>
                                                <td>
                                                    14
                                                </td>
                                                <td>
                                                    24
                                                </td>
                                                <td>
                                                    5
                                                </td>
                                                <td>
                                                    15
                                                </td>
                                                <td>
                                                    25
                                                </td>
                                                <td>
                                                    6
                                                </td>
                                                <td>
                                                    16
                                                </td>
                                                <td>
                                                    26
                                                </td>
                                                <td>
                                                    7
                                                </td>
                                                <td>
                                                    17
                                                </td>
                                                <td>
                                                    27
                                                </td>
                                                <td>
                                                    8
                                                </td>
                                                <td>
                                                    18
                                                </td>
                                                <td>
                                                    9
                                                </td>
                                                <td>
                                                    19
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    直选
                                                </td>
                                                <td>
                                                    000
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    777
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    444
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    111
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td class="xl29">
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    888
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    555
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    222
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    999
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    666
                                                </td>
                                                <td>
                                                    333
                                                </td>
                                                <td>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td rowspan="5">
                                                    组选 3
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    118
                                                </td>
                                                <td>
                                                    668
                                                </td>
                                                <td>
                                                    001
                                                </td>
                                                <td>
                                                    119
                                                </td>
                                                <td>
                                                    669
                                                </td>
                                                <td>
                                                    002
                                                </td>
                                                <td>
                                                    228
                                                </td>
                                                <td>
                                                    778
                                                </td>
                                                <td>
                                                    003
                                                </td>
                                                <td>
                                                    229
                                                </td>
                                                <td>
                                                    779
                                                </td>
                                                <td>
                                                    004
                                                </td>
                                                <td>
                                                    338
                                                </td>
                                                <td>
                                                    996
                                                </td>
                                                <td>
                                                    005
                                                </td>
                                                <td>
                                                    339
                                                </td>
                                                <td>
                                                    889
                                                </td>
                                                <td>
                                                    006
                                                </td>
                                                <td>
                                                    448
                                                </td>
                                                <td>
                                                    998
                                                </td>
                                                <td>
                                                    007
                                                </td>
                                                <td>
                                                    449
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    008
                                                </td>
                                                <td>
                                                    558
                                                </td>
                                                <td>
                                                    009
                                                </td>
                                                <td>
                                                    559
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    226
                                                </td>
                                                <td>
                                                    776
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    227
                                                </td>
                                                <td>
                                                    885
                                                </td>
                                                <td>
                                                    011
                                                </td>
                                                <td>
                                                    336
                                                </td>
                                                <td>
                                                    886
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    337
                                                </td>
                                                <td>
                                                    887
                                                </td>
                                                <td>
                                                    112
                                                </td>
                                                <td>
                                                    446
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    113
                                                </td>
                                                <td>
                                                    447
                                                </td>
                                                <td>
                                                    997
                                                </td>
                                                <td>
                                                    114
                                                </td>
                                                <td>
                                                    556
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    115
                                                </td>
                                                <td>
                                                    557
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    116
                                                </td>
                                                <td>
                                                    774
                                                </td>
                                                <td>
                                                    117
                                                </td>
                                                <td>
                                                    667
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    334
                                                </td>
                                                <td>
                                                    884
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    335
                                                </td>
                                                <td>
                                                    993
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    552
                                                </td>
                                                <td>
                                                    994
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    445
                                                </td>
                                                <td>
                                                    995
                                                </td>
                                                <td>
                                                    220
                                                </td>
                                                <td>
                                                    554
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    221
                                                </td>
                                                <td>
                                                    663
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    330
                                                </td>
                                                <td>
                                                    664
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    223
                                                </td>
                                                <td>
                                                    665
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    224
                                                </td>
                                                <td>
                                                    882
                                                </td>
                                                <td>
                                                    225
                                                </td>
                                                <td>
                                                    775
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    442
                                                </td>
                                                <td>
                                                    992
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    443
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    660
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    553
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    662
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    771
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    772
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    331
                                                </td>
                                                <td>
                                                    773
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    332
                                                </td>
                                                <td>
                                                    990
                                                </td>
                                                <td>
                                                    441
                                                </td>
                                                <td>
                                                    883
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    550
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    551
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    661
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    770
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    &nbsp;
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    880
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    881
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    440
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    991
                                                </td>
                                            </tr>
                                            <tr>
                                                <td rowspan="10">
                                                    组选 6
                                                </td>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    019
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    389
                                                </td>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    029
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    489
                                                </td>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    039
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    589
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    012
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    049
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    689
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    013
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    059
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    789
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    014
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    069
                                                </td>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    015
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    079
                                                </td>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    016
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    089
                                                </td>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    017
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    189
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    018
                                                </td>
                                                <td bgcolor="#ffffff">
                                                    289
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    028
                                                </td>
                                                <td>
                                                    479
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    038
                                                </td>
                                                <td>
                                                    579
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    048
                                                </td>
                                                <td>
                                                    679
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    058
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    068
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    023
                                                </td>
                                                <td>
                                                    078
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    024
                                                </td>
                                                <td>
                                                    169
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    025
                                                </td>
                                                <td>
                                                    179
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    026
                                                </td>
                                                <td>
                                                    279
                                                </td>
                                                <td>
                                                    027
                                                </td>
                                                <td>
                                                    379
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    037
                                                </td>
                                                <td>
                                                    569
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    047
                                                </td>
                                                <td>
                                                    678
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    057
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    067
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    149
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    159
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    123
                                                </td>
                                                <td>
                                                    178
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    034
                                                </td>
                                                <td>
                                                    269
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    035
                                                </td>
                                                <td>
                                                    369
                                                </td>
                                                <td>
                                                    036
                                                </td>
                                                <td>
                                                    469
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    046
                                                </td>
                                                <td>
                                                    578
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    056
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    129
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    139
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    158
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    168
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    259
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    124
                                                </td>
                                                <td>
                                                    278
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    125
                                                </td>
                                                <td>
                                                    378
                                                </td>
                                                <td>
                                                    045
                                                </td>
                                                <td>
                                                    478
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    127
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    128
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    138
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    148
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    167
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    249
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    268
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    359
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    134
                                                </td>
                                                <td>
                                                    459
                                                </td>
                                                <td>
                                                    126
                                                </td>
                                                <td>
                                                    568
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    136
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    137
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    147
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    157
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    239
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    258
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    349
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    368
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    468
                                                </td>
                                                <td>
                                                    135
                                                </td>
                                                <td>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    145
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    146
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    156
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    238
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    248
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    267
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    358
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    458
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    567
                                                </td>
                                                <td>
                                                    234
                                                </td>
                                                <td>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                    235
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    236
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    237
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    247
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    257
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    348
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    367
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    467
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    245
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    246
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    256
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    347
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    357
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    457
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td bgcolor="#ffffff">
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    345
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    346
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    356
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    456
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    组选注数
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    22
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    单选注数
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    100
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    100
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    100
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    100
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    100
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    100
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    100
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    100
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    100
                                                </td>
                                                <td>
                                                </td>
                                                <td>
                                                    100
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                
<div class="wrap">
         <p>
                                       由 0-9 十个数字组成的三位数号码，三个数字相加之和的尾数称为“和数尾”。和数尾同样有 0-9 十个组合，每一个尾数里都包含 1
                                            注直选的“豹子”， 9 注“组选 3” 和 12 注“组选 6” 号码。和数尾可分为单点的 1 ， 3 ， 5 ， 7 ， 9 和双点的 0 ， 2 ， 4 ，
                                            6 ， 8 同时又可分为小点的 0 ， 1 ， 2 ， 3 ， 4 和大点的 5 ， 6 ， 7 ， 8 ， 9 。<br>
                                            根据对各个尾数，单双点，大小点，除三余数的出号跟踪，当判断某一尾数中出希望较大时，即可在相应尾数中进行选号
                                            <br />

 <a href="<%= _Site.Url %>" target="_blank">
                                <a href='FC3D_ZHXT.aspx' target='mainFrame'>
                                    综合分布遗漏走势图</a> | <a href='FC3D_C3YS.aspx' target='mainFrame'>除三余数形态遗漏走势图</a>
                            | <a href='FC3D_ZHZST.aspx' target='mainFrame'>质合形态遗漏走势图</a> | <a href='FC3D_XTZST.aspx'
                                target='mainFrame'>形态遗漏走势图</a><a href='FC3D_KDZST.aspx' target='mainFrame'>跨度遗漏走势图</a>
                            | <a href='FC3D_HZZST.aspx' target='mainFrame'>和值遗漏走势图</a> | <a href='FC3D_DZXZST.aspx'
                                target='mainFrame'>大中小形态遗漏走势图</a> |  <br /><a href='FC3D_C3YS_HTML.aspx' target='mainFrame'>
                                    除三余数号码分区表走势图</a> |<a href='FC3D_2CHW.aspx' target='mainFrame'>二次和尾差尾查询表走势图</a>
                            | <a href='FC3D_DSHM.aspx' target='mainFrame'>单双点号码分区表走势图</a> |<a href='FC3D_DTHM.aspx'
                                target='mainFrame'>胆托号码分区表走势图</a>| <a href='FC3D_DX_JO.aspx' target='mainFrame'>大小—奇偶号码分区表走势图</a>
                            | <a href='FC3D_HSWH.aspx' target='mainFrame'>和数尾号码分区表走势图</a> | <br /> <a href='FC3D_HSZ.aspx'
                                target='mainFrame'>和数值号码分区表走势图</a> | <a href='FC3D_KDZH.aspx' target='mainFrame'>跨度组合分区表走势图</a>
                            | <a href='FC3D_JO_DX.aspx' target='mainFrame'>奇偶—大小号码分区表走势图</a> | <a href='FC3D_LHZH.aspx'
                                target='mainFrame'>连号组合分区表走势图</a> | <a href='FC3D_ZS.aspx' target='mainFrame'>质数号码分区表走势图</a>
                       </p>
            </div>
         </div>
        <uc1:webfoot id="WebFoot1" runat="server" />

    </form>
</body>
</html>
